# -*- coding: utf-8 -*-
"""Mapa nombre de país (español, como viene en la data) -> abreviación para el id.
Preferentemente ISO 3166-1 alpha-2; para no-países o casos ambiguos, código corto propio.
"""

COUNTRY_MAP = {
    "afganistán": "af",
    "albania": "al",
    "alemania": "de",
    "angola": "ao",
    "arabia saudí": "sa",
    "argelia": "dz",
    "argentina": "ar",
    "armenia": "am",
    "australia": "au",
    "austria": "at",
    "azerbaiyán": "az",
    "bahamas": "bs",
    "baréin": "bh",
    "bailía de jersey": "je",
    "bangladesh": "bd",
    "barbados": "bb",
    "bélgica": "be",
    "belice": "bz",
    "bermuda": "bm",
    "biafra": "bia",
    "bielorrusia": "by",
    "birmania": "mm",
    "bolivia": "bo",
    "botswana": "bw",
    "bosnia y herzegovina": "ba",
    "brasil": "br",
    "brunei": "bn",
    "bulgaria": "bg",
    "burundi": "bi",
    "bután": "bt",
    "cabo verde": "cv",
    "camboya": "kh",
    "canadá": "ca",
    "chile": "cl",
    "china": "cn",
    "chipre": "cy",
    "colombia": "co",
    "comoras": "km",
    "corea": "kor",
    "corea del norte": "kp",
    "corea del sur": "kr",
    "costa rica": "cr",
    "croacia": "hr",
    "cuba": "cu",
    "curazao": "cw",
    "curazao y san martín": "cwsx",
    "dinamarca": "dk",
    "ecuador": "ec",
    "egipto": "eg",
    "el congo": "cd",
    "emiratos árabes": "ae",
    "eritrea": "er",
    "escocia": "sct",
    "eslovenia": "si",
    "españa": "es",
    "estados unidos": "us",
    "estados del caribe oriental": "xcd",
    "estonia": "ee",
    "etiopía": "et",
    "filipinas": "ph",
    "finlandia": "fi",
    "fiyi": "fj",
    "francia": "fr",
    "gambia": "gm",
    "georgia": "ge",
    "ghana": "gh",
    "gran bretaña": "gb",
    "grecia": "gr",
    "guatemala": "gt",
    "guernsey": "gg",
    "guinea": "gn",
    "guinea-bisáu": "gw",
    "guyana": "gy",
    "haití": "ht",
    "honduras": "hn",
    "hong kong": "hk",
    "hungría": "hu",
    "india": "in",
    "indonesia": "id",
    "irak": "iq",
    "irán": "ir",
    "irlanda del norte": "nir",
    "islandia": "is",
    "islas caimán": "ky",
    "islas cook": "ck",
    "isla de man": "im",
    "islas salomón": "sb",
    "israel": "il",
    "italia": "it",
    "jamaica": "jm",
    "japón": "jp",
    "jordania": "jo",
    "kazajistán": "kz",
    "kenia": "ke",
    "kirguistán": "kg",
    "kuwait": "kw",
    "laos": "la",
    "lesotho": "ls",
    "líbano": "lb",
    "liberia": "lr",
    "libia": "ly",
    "lituania": "lt",
    "macao (china)": "mo",
    "macedonia del norte": "mk",
    "madagascar": "mg",
    "malasia": "my",
    "malaui": "mw",
    "maldivas": "mv",
    "marruecos": "ma",
    "mauricio": "mu",
    "mauritania": "mr",
    "méxico": "mx",
    "moldavia": "md",
    "mongolia": "mn",
    "mozambique": "mz",
    "namibia": "na",
    "nepal": "np",
    "nicaragua": "ni",
    "nigeria": "ng",
    "noruega": "no",
    "nueva zelanda": "nz",
    "omán": "om",
    "países bajos": "nl",
    "pakistán": "pk",
    "papúa nueva guinea": "pg",
    "paraguay": "py",
    "perú": "pe",
    "polonia": "pl",
    "portugal": "pt",
    "qatar": "qa",
    "rep. checa": "cz",
    "rep. dominicana": "do",
    "ruanda": "rw",
    "rumania": "ro",
    "rusia": "ru",
    "samoa": "ws",
    "santo tomé y príncipe": "st",
    "serbia": "rs",
    "seychelles": "sc",
    "sierra leona": "sl",
    "singapur": "sg",
    "siria": "sy",
    "somalia": "so",
    "somalilandia": "sml",
    "sri lanka": "lk",
    "suazilandia": "sz",
    "sudáfrica": "za",
    "sudán": "sd",
    "sudán del sur": "ss",
    "suecia": "se",
    "suiza": "ch",
    "surinam": "sr",
    "tailandia": "th",
    "taiwán": "tw",
    "tanzania": "tz",
    "tayikistán": "tj",
    "tonga": "to",
    "transnistria": "pmr",
    "trinidad y tobago": "tt",
    "túnez": "tn",
    "turkmenistán": "tm",
    "turquía": "tr",
    "ucrania": "ua",
    "uganda": "ug",
    "unión europea": "eu",
    "uruguay": "uy",
    "uzbekistán": "uz",
    "vanuatu": "vu",
    "venezuela": "ve",
    "vietnam": "vn",
    "vietnam del sur": "vns",
    "yemen": "ye",
    "yibuti": "dj",
    "yugoslavia": "yu",
    "zaire": "zr",
    "zambia": "zm",
    "zimbabue": "zw",
}

# nombre en español (como viene en la data) -> nombre en inglés
COUNTRY_EN = {
    "afganistán": "Afghanistan",
    "albania": "Albania",
    "alemania": "Germany",
    "angola": "Angola",
    "arabia saudí": "Saudi Arabia",
    "argelia": "Algeria",
    "argentina": "Argentina",
    "armenia": "Armenia",
    "australia": "Australia",
    "austria": "Austria",
    "azerbaiyán": "Azerbaijan",
    "bahamas": "Bahamas",
    "baréin": "Bahrain",
    "bailía de jersey": "Bailiwick of Jersey",
    "bangladesh": "Bangladesh",
    "barbados": "Barbados",
    "bélgica": "Belgium",
    "belice": "Belize",
    "bermuda": "Bermuda",
    "biafra": "Biafra",
    "bielorrusia": "Belarus",
    "birmania": "Myanmar",
    "bolivia": "Bolivia",
    "botswana": "Botswana",
    "bosnia y herzegovina": "Bosnia and Herzegovina",
    "brasil": "Brazil",
    "brunei": "Brunei",
    "bulgaria": "Bulgaria",
    "burundi": "Burundi",
    "bután": "Bhutan",
    "cabo verde": "Cape Verde",
    "camboya": "Cambodia",
    "canadá": "Canada",
    "chile": "Chile",
    "china": "China",
    "chipre": "Cyprus",
    "colombia": "Colombia",
    "comoras": "Comoros",
    "corea": "Korea",
    "corea del norte": "North Korea",
    "corea del sur": "South Korea",
    "costa rica": "Costa Rica",
    "croacia": "Croatia",
    "cuba": "Cuba",
    "curazao": "Curaçao",
    "curazao y san martín": "Curaçao and Sint Maarten",
    "dinamarca": "Denmark",
    "ecuador": "Ecuador",
    "egipto": "Egypt",
    "el congo": "Democratic Republic of the Congo",
    "emiratos árabes": "United Arab Emirates",
    "eritrea": "Eritrea",
    "escocia": "Scotland",
    "eslovenia": "Slovenia",
    "españa": "Spain",
    "estados unidos": "United States",
    "estados del caribe oriental": "Eastern Caribbean States",
    "estonia": "Estonia",
    "etiopía": "Ethiopia",
    "filipinas": "Philippines",
    "finlandia": "Finland",
    "fiyi": "Fiji",
    "francia": "France",
    "gambia": "Gambia",
    "georgia": "Georgia",
    "ghana": "Ghana",
    "gran bretaña": "Great Britain",
    "grecia": "Greece",
    "guatemala": "Guatemala",
    "guernsey": "Guernsey",
    "guinea": "Guinea",
    "guinea-bisáu": "Guinea-Bissau",
    "guyana": "Guyana",
    "haití": "Haiti",
    "honduras": "Honduras",
    "hong kong": "Hong Kong",
    "hungría": "Hungary",
    "india": "India",
    "indonesia": "Indonesia",
    "irak": "Iraq",
    "irán": "Iran",
    "irlanda del norte": "Northern Ireland",
    "islandia": "Iceland",
    "islas caimán": "Cayman Islands",
    "islas cook": "Cook Islands",
    "isla de man": "Isle of Man",
    "islas salomón": "Solomon Islands",
    "israel": "Israel",
    "italia": "Italy",
    "jamaica": "Jamaica",
    "japón": "Japan",
    "jordania": "Jordan",
    "kazajistán": "Kazakhstan",
    "kenia": "Kenya",
    "kirguistán": "Kyrgyzstan",
    "kuwait": "Kuwait",
    "laos": "Laos",
    "lesotho": "Lesotho",
    "líbano": "Lebanon",
    "liberia": "Liberia",
    "libia": "Libya",
    "lituania": "Lithuania",
    "macao (china)": "Macau (China)",
    "macedonia del norte": "North Macedonia",
    "madagascar": "Madagascar",
    "malasia": "Malaysia",
    "malaui": "Malawi",
    "maldivas": "Maldives",
    "marruecos": "Morocco",
    "mauricio": "Mauritius",
    "mauritania": "Mauritania",
    "méxico": "Mexico",
    "moldavia": "Moldova",
    "mongolia": "Mongolia",
    "mozambique": "Mozambique",
    "namibia": "Namibia",
    "nepal": "Nepal",
    "nicaragua": "Nicaragua",
    "nigeria": "Nigeria",
    "noruega": "Norway",
    "nueva zelanda": "New Zealand",
    "omán": "Oman",
    "países bajos": "Netherlands",
    "pakistán": "Pakistan",
    "papúa nueva guinea": "Papua New Guinea",
    "paraguay": "Paraguay",
    "perú": "Peru",
    "polonia": "Poland",
    "portugal": "Portugal",
    "qatar": "Qatar",
    "rep. checa": "Czech Republic",
    "rep. dominicana": "Dominican Republic",
    "ruanda": "Rwanda",
    "rumania": "Romania",
    "rusia": "Russia",
    "samoa": "Samoa",
    "santo tomé y príncipe": "São Tomé and Príncipe",
    "serbia": "Serbia",
    "seychelles": "Seychelles",
    "sierra leona": "Sierra Leone",
    "singapur": "Singapore",
    "siria": "Syria",
    "somalia": "Somalia",
    "somalilandia": "Somaliland",
    "sri lanka": "Sri Lanka",
    "suazilandia": "Eswatini",
    "sudáfrica": "South Africa",
    "sudán": "Sudan",
    "sudán del sur": "South Sudan",
    "suecia": "Sweden",
    "suiza": "Switzerland",
    "surinam": "Suriname",
    "tailandia": "Thailand",
    "taiwán": "Taiwan",
    "tanzania": "Tanzania",
    "tayikistán": "Tajikistan",
    "tonga": "Tonga",
    "transnistria": "Transnistria",
    "trinidad y tobago": "Trinidad and Tobago",
    "túnez": "Tunisia",
    "turkmenistán": "Turkmenistan",
    "turquía": "Turkey",
    "ucrania": "Ukraine",
    "uganda": "Uganda",
    "unión europea": "European Union",
    "uruguay": "Uruguay",
    "uzbekistán": "Uzbekistan",
    "vanuatu": "Vanuatu",
    "venezuela": "Venezuela",
    "vietnam": "Vietnam",
    "vietnam del sur": "South Vietnam",
    "yemen": "Yemen",
    "yibuti": "Djibouti",
    "yugoslavia": "Yugoslavia",
    "zaire": "Zaire",
    "zambia": "Zambia",
    "zimbabue": "Zimbabwe",
}
